version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - note-app
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: note-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rejohn
      MYSQL_DATABASE: db_note_app
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - note-app

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: note-phpmyadmin
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PASSWORD: rejohn
    ports:
      - "8080:80"
    networks:
      - note-app

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: note-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    networks:
      - note-app
    depends_on:
      - php
  
  frontend:
    build: ./frontend
    command: npm run dev  # Adjust this to your development command
    volumes:
      - ./frontend:/app  # Maps frontend directory to /app in container
      - /app/node_modules # Avoid overwriting node_modules
    ports:
      - 3000:3000  # Maps port 3000 on host to 3000 in container
    depends_on:
      - php

volumes:
  mysql-data:

networks:
  note-app:
